# This ebuild was auto-generated by homeassistant script, and the script was not able to find a better candidate.
EAPI=8

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{12,13{,t}} )
PYPI_NO_NORMALIZE=1

inherit distutils-r1 pypi

DESCRIPTION=""
HOMEPAGE=""

LICENSE=""
SLOT="0"
KEYWORDS=""
IUSE="test"

GENERATED_DEPEND=""
RDEPEND="${GENERATED_DEPEND}"
BDEPEND="test? ( ${GENERATED_DEPEND} )"

EPYTEST_XDIST=1
distutils_enable_tests pytest
